spring.config.import=optional:application-dev.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PSW}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.db.connection-timeout=3000ms
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000